apiVersion: extensions/v1beta1 
kind: DaemonSet
metadata:
  name: fluentd-elasticsearch
  namespace: kube-system
  labels:
    k8s-app: fluentd-elasticsearch
spec:
  template:
    metadata:
      namespace: kube-system
      labels:
        k8s-app: fluentd-elasticsearch
    spec:
      containers:
      - name: fluentd-elasticsearch
        image: fluentd-elasticsearch:1.9
        imagePullPolicy: Never
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        env:
          - name: FLUENTD_ARGS
            value: -q
        volumeMounts:
          - name: containers
            mountPath: /var/lib/docker/containers
          - name: varlog
            mountPath: /varlog
          - name: podlog
            mountPath: /var/lib/kubelet/pods
      volumes:
        - name: containers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlog
          hostPath:
            path: /var/log
        - name: podlog
          hostPath:
            path: /var/lib/kubelet/pods
