apiVersion: v1
kind: Pod
metadata:
  name: fluentd
spec:
  containers:
  - name: fluentd-es
    image: fluentd-elasticsearch:1.9
    imagePullPolicy: Never
    env:
      - name: FLUENTD_ARGS
        value: -qq
    volumeMounts:
      - name: containers
        mountPath: /var/lib/docker/containers
      - name: varlog
        mountPath: /varlog
      - name: podlog
        mountPath: /var/lib/kubelet/pods
  volumes:
    - name: containers
      hostPath:
        path: /var/lib/docker/containers
    - name: varlog
      hostPath:
        path: /var/log
    - name: podlog
      hostPath:
        path: /var/lib/kubelet/pods
